
--	CRIAÇÃO DA TABELA
CREATE TABLE TESTETRIGGER(ID INT IDENTITY(1,1) PRIMARY KEY, NOME VARCHAR(50), IDADE INT)

--	INSERINDO OS DADOS
INSERT INTO TESTETRIGGER(NOME, IDADE) VALUES ('João', 54)
INSERT INTO TESTETRIGGER(NOME, IDADE) VALUES ('Daiane', 33)
INSERT INTO TESTETRIGGER(NOME, IDADE) VALUES ('Lucas', 20)

--	CRIANDO TABELA DE HISTÓRICO
CREATE TABLE TESTETRIGGERHISTORICO(ID INT IDENTITY(1,1) PRIMARY KEY, NOME VARCHAR(50), IDADE INT, DATAALTERACAO SMALLDATETIME)

SELECT* FROM TESTETRIGGER
SELECT* FROM TESTETRIGGERHISTORICO

--	CRIANDO TRIGGER
CREATE TRIGGER TR_BACKUP_TESTE										--	Nome da trigger
ON TESTETRIGGER														--	Tabela origem da ação
FOR UPDATE															--	'FOR' indica que será executado antes 'UPDATE' indica o comando
AS									
BEGIN
	INSERT INTO TESTETRIGGERHISTORICO(NOME, IDADE, DATAALTERACAO)	--	Insert dos dados
	SELECT NOME, IDADE, GETDATE() FROM deleted;						--	Indica que inserirá os campos correspondentes ao NOME, IDADE da tabela TESTETRIGGER e pegará a data e hora atual, obtendo os dados antes de serem alterados
END

update TESTETRIGGER SET NOME = 'João mais o sobrenome begin' where id = 1

SELECT* FROM TESTETRIGGER
SELECT* FROM TESTETRIGGERHISTORICO


